# Basic settings
locale: "en-US"
title: "Yang Penghui / Personal Homepage"
title_separator: "-"
name: "Yang Penghui"
description: "A senior undergraduate student at Tsinghua University. Interests: LLMs, multimodal learning, energy & AI."
url: "https://yangpenghui.github.io"
baseurl: ""  # 必须留空（用户主页仓库）

# Remote theme (use academicpages)
remote_theme: "academicpages/academicpages.github.io"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

# Author (replace values)
author:
  name: "Yang Penghui"
  avatar: "/images/profile.jpg"   # 请确保 images 下有对应文件
  bio: "Undergraduate student at Tsinghua University. Research: LLMs, multimodal learning."
  location: "Beijing, China"
  github: "yangpenghui"
  email: "your_email@example.com"

# Collections example
collections:
  publications:
    output: true
    permalink: /publications/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Defaults & Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Asia/Shanghai
include:
  - _pages
